### ISSUE TITLE
Received warning when trying to add wormhole as a dependancy

### ISSUE THREAD

**Issue by yonatann** [renderedtext/wormhole#22]
Hi, 
I receive the following warning after adding wormhole as a dependency:

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name

**Comment by predrag-rakic** [comment]
@yonatann Which version of elixir are you using?

**Comment by yonatann** [comment]
Hi @predrag-rakic , I am using the following erlang/elixir setup:

Erlang/OTP 19 [erts-8.2] [source-fbd2db2] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.4.1

**Comment by predrag-rakic** [comment]
@yonatann should be fixed now

**Comment by predrag-rakic** [comment]
Please reopen if you still get warnings
