### ISSUE TITLE
Option to suppress warn logs on failed callback execution 

### ISSUE THREAD

**Issue by DamjanBecirovic** [renderedtext/wormhole#30]
If callback function invoked from Wormhole fails, Wormhole produces warn level log which contains both function and it's arguments. Currently there is no way to suppress this log, and it can be security issue if callback function arguments contain sensitive data.

It would be great if option to suppress this log is added.

**Comment by predrag-rakic** [comment]
@DamjanBecirovic 
Already implemented but not documented.
Documented in https://github.com/renderedtext/wormhole/pull/31
